#pragma once

//**************************************************************************/
// Copyright (c) 2019 Autodesk, Inc.
// All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
//**************************************************************************/
// DESCRIPTION: Includes for Plugins
// AUTHOR: 
//***************************************************************************/

#include <Qt/QMaxParamBlockWidget.h>

// This namespace is defined in the header generated by Qt
namespace Ui {
	class ClustModRollup;
};

// Inherit from QMaxParamBlockWidget
class ClustModRollup : public MaxSDK::QMaxParamBlockWidget
{
	// Connects us to Qt's meta-object system
	Q_OBJECT

public:
	explicit ClustModRollup(QWidget* parent = nullptr);
	~ClustModRollup(void);

	// Virtual functions required by QMaxParamBlockWidget
	virtual void SetParamBlock(ReferenceMaker* /*owner*/, IParamBlock2* const /*param_block*/) override {};
	virtual void UpdateUI(const TimeValue /*t*/) override {};
	virtual void UpdateParameterUI(const TimeValue /*t*/, const ParamID /*param_id*/, const int /*tab_index*/) override {};

private:
	Ui::ClustModRollup* ui = nullptr;

};
