//**************************************************************************/
// Copyright (c) 2025 Autodesk, Inc.
// All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
//**************************************************************************/

// This file was generated by maxpake_task_generate_sdk_headers.py
#define VERSION_STRING "Devi with PDBs D4098_RL_x64 02-13-2025 11:27 bfba912deae086d84d826b4bd09e6d200208bd03"
#define VERSION_INT 4098
