//**************************************************************************/
// Copyright (c) 2025 Autodesk, Inc.
// All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
//**************************************************************************/

// This file was generated by maxpake_task_generate_sdk_headers.py
#ifndef BUILDVER_H
#define BUILDVER_H

#include "BuildWarnings.h"

// These includes rely on symbols defined in this file. Don't move them at the top of the file.
// No need to include them in any other file.
#include "ProductFileSupport.h"
#include "ProductDefaults.h"
#endif
